export * from './jefe-operaciones.repository';
export * from './mecanico.repository';
export * from './notificaciones.repository';
export * from './propietario.repository';
export * from './repuesto.repository';
export * from './revision.repository';
export * from './sedes.repository';
export * from './usuario.repository';
export * from './vehiculo.repository';
